const Actions = {
  GET_LIST_TODO: 'GET_LIST_TODO',
  GET_LIST_TODO_SUCCESS: 'GET_LIST_TODO_SUCCESS',
  ADD_TODO: 'ADD_TODO',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  REMOVE_TODO: 'REMOVE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  REMOVE_MULTIL_DATA: 'REMOVE_MULTIL_DATA',
  EDIT_TEXT: 'EDIT_TEXT',
};
export default Actions;
